### ISSUE TITLE
Can't load dependencies 

### ISSUE THREAD

**Issue by gwc4github** [arXiv/arxiv-browse#185]
**Describe the bug**
I think I am missing a weird dependency. I keep running it app.py and adding dependencies as they are found but have gotten stuck here:
```
Traceback (most recent call last):
  File "/.../arxiv-browse-0.3.2.5/app.py", line 2, in <module>
    from browse.factory import create_web_app
  File "/..../arxiv-browse-0.3.2.5/browse/factory.py", line 15, in <module>
    from arxiv.users.auth import Auth
ModuleNotFoundError: No module named 'arxiv.users'

Process finished with exit code 1
```
When I try to add  pip install arxiv-auth
`Collecting arxiv-auth
  Using cached arxiv-auth-0.4.2.tar.gz (35 kB)
Collecting pycountry
  Using cached pycountry-20.7.3.tar.gz (10.1 MB)
Requirement already satisfied: sqlalchemy in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from arxiv-auth) (1.3.19)
Collecting mimesis
  Using cached mimesis-4.1.2.tar.gz (2.8 MB)
Collecting mysqlclient
  Using cached mysqlclient-2.0.1.tar.gz (87 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xh/xfrbbd5d74g0p6wcxx2ymq3m0000gn/T/pip-install-kj4hzv7p/mysqlclient/setup.py'"'"'; __file__='"'"'/private/var/folders/xh/xfrbbd5d74g0p6wcxx2ymq3m0000gn/T/pip-install-kj4hzv7p/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/xh/xfrbbd5d74g0p6wcxx2ymq3m0000gn/T/pip-pip-egg-info-f06mv1uj
         cwd: /private/var/folders/xh/xfrbbd5d74g0p6wcxx2ymq3m0000gn/T/pip-install-kj4hzv7p/mysqlclient/
    Complete output (12 lines):
    /bin/sh: mysql_config: command not found
    /bin/sh: mariadb_config: command not found
    /bin/sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/xh/xfrbbd5d74g0p6wcxx2ymq3m0000gn/T/pip-install-kj4hzv7p/mysqlclient/setup.py", line 15, in <module>
        metadata, options = get_config()
      File "/private/var/folders/xh/xfrbbd5d74g0p6wcxx2ymq3m0000gn/T/pip-install-kj4hzv7p/mysqlclient/setup_posix.py", line 65, in get_config
        libs = mysql_config("libs")
      File "/private/var/folders/xh/xfrbbd5d74g0p6wcxx2ymq3m0000gn/T/pip-install-kj4hzv7p/mysqlclient/setup_posix.py", line 31, in mysql_config
        raise OSError("{} not found".format(_mysql_config_path))
    OSError: mysql_config not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

Note that I am using PyCharm but I don't think that makes a differnce.

**To Reproduce**
  Download zip file
  Uncompress
  Make as project 
  run/install missing dependence/repeat

**Expected behavior**
   Run sample program

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser N/A
 - Python Version 3.8.2
- PyCharm 2020.2
Other versions:
![image](https://user-images.githubusercontent.com/3164663/92335847-09827b80-f069-11ea-8a7d-7eb005ee85b3.png)

![image](https://user-images.githubusercontent.com/3164663/92335886-536b6180-f069-11ea-98b9-11f50c59d6f9.png)

**Comment by bdc34** [comment]
The dependencies have changed a lot since 2020 and they work in the GH actions.
