### ISSUE TITLE
CORE Recommender links

### ISSUE THREAD

**Issue by mhl10** [arXiv/arxiv-browse#205]
As reported by @jimentwood:

When you right click on a paper recommended in the "Recommenders and Search Tools" (Part of arxiv labs under an article), and click "open link in new tab", it will reopen the  same url you're currently on. Expectation is that it opens the URL of the actual recommended paper. If you left click on the recommended paper directly, everything behaves as expected and the recommended paper opens in new tab.

Another way to test for this is to right click, then use:"Copy link location" in context menu and you will see that it is the same link as the original.

**Comment by mhl10** [comment]
The CORE Recommender js appears to be using the `data-value` attribute to perform the redirect on click:
```
<a class="documentTpl" href="#" id="141535124" 
data-value="https://core.ac.uk/recommender/redirect?url=http://arxiv.org/abs/1712.01053&amp;otherRecs=141535124,146480357,334834689,186276017,2387887">
```
@viktor-yakubiv would it be possible to update the script to capture right clicks (`oncontextmenu` events) and/or show the actual link in the `href` attribute?

**Comment by viktor-yakubiv** [comment]
@jimentwood and @mhl10, thank you for spotting this and tagging me here. I am sorry, this accessibility issue happened, it could be and must be fixed as soon as possible. I will reply to this thread when it's done.

**Comment by viktor-yakubiv** [comment]
@mhl10 and @jimentwood, sorry this took us a while. The fix is already merged and published. I've just tested it on arXiv.org and it works just fine. I assume you can freely close the issue. Let us know if something else is needed 🙂

**Comment by jimentwood** [comment]
Thanks @viktor-yakubiv ! I let the user who initially reported this know the fix is deployed.
