### ISSUE TITLE
Bibliographic Explorer - Semantic Scholar request fails - CORS Mission allow origin

### ISSUE THREAD

**Issue by Mattwmaster58** [arXiv/arxiv-browse#226]
**Describe the bug**
The request to Semantic Scholar is missing a header causing the request to fail.

**To Reproduce**
1. Go to any paper's url ([example](https://arxiv.org/abs/2105.14481))
2. Ensure 'Bibliographic Explorer' is on
3. Observe error:
![image](https://user-images.githubusercontent.com/26337069/120549720-f0251a80-c3c1-11eb-8453-b653a3062efb.png)

My browser's dev console notes "CORS Missing Allow Origin" on the preflight request. Adding `Access-Control-Allow-Origin: *` to the request manually allows the request to successfully complete.

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser: Firefox 91, Chrome 92

**Comment by bdc34** [comment]
This appears to be working now. Sorry for the delay.

**Comment by pavank** [comment]
I am seeing this error again. For both Semantic Scholar and Prophy

OS: Ubuntu Desktop 22.04.3
Chrome Browser: Version 116.0.5845.96 (Official Build) (64-bit)
Firefox Browser:Version 105.0.2 (64-bit) Same error
![Screenshot from 2023-08-21 21-28-30](https://github.com/arXiv/arxiv-browse/assets/598405/9602a6a9-3e76-4466-b954-fc421f8a2c5c)

**Comment by YZsZY** [comment]
Hello, how to fix this bug~ It appears again these dayo(╥﹏╥)o

**Comment by tdietterich** [comment]
I have been seeing this issue for a while. I'm running the latest Firefox with ublock origin disabled for both arxiv and semanticscholar

**Comment by yeshwanth95** [comment]
I am also facing this issue. Has anyone managed to fix this?

**Comment by malbergo** [comment]
Same issue here!

**Comment by faizanahemad** [comment]
Same issue here

**Comment by Westlifers** [comment]
idk why but I'm facing this issue for weeks...

**Comment by tdietterich** [comment]
I am experiencing this again. As with others, this is in Firefox with ublock origin disabled. Also fails in Chrome.

**Comment by hachreak** [comment]
same issue!
