### ISSUE TITLE
Add doi and url to the bibtex export of preprints

### ISSUE THREAD

**Issue by daringli** [arXiv/arxiv-browse#437]
**Is your feature request related to a problem? Please describe.**
Many journal bibtex style files (.bst) do not support arXiv preprints but most support doi or url fields. When citing an arXiv preprint for some journal publications, I thus have to add these fields manually.
Here are examples of bibtex exports before and after these extra fields have been added:
[bibtex_export_after.txt](https://github.com/arXiv/arxiv-browse/files/13481243/bibtex_export_after.txt)
[bibtex_export_before.txt](https://github.com/arXiv/arxiv-browse/files/13481244/bibtex_export_before.txt)

**Describe the solution you'd like**
Add the arXiv doi and url to fields in the bibtex export for preprints.

**Additional context**
I've created a corresponding pull request at https://github.com/arXiv/arxiv-browse/pull/436

**Comment by jweiskoff** [comment]
This has been added.
