### ISSUE TITLE
Browse should be more mobile-friendly

### ISSUE THREAD

**Issue by mhl10** [arXiv/arxiv-browse#49]
From https://librt.library.cornell.edu/Ticket/Display.html?id=249881

> 
> I read the arXiv on a mobile phone while having breakfast. Would be great if there was a mobile friendly presentation of the pages. I guess this is a feature request from an old dude with poor eyes and small iPhone :slightly_smiling_face:
> 
> Thanks so much for having started and maintained this service. arXiv has transformed research publishing.
>

**Comment by cben** [comment]
On Android, mobile layout is a bit better, but mathjax formulas are small compared to surrounding text:
in Firefox 68.0  (Firefox Preview app):
![Screenshot_android_firefox](https://user-images.githubusercontent.com/273688/62754941-9d56d200-ba7a-11e9-8e18-4246b1909458.jpg)

In firefox switching to desktop mode renders mathjax ok, though layout is too wide making all text small:
![Screenshot_android_firefox_desktop_mode](https://user-images.githubusercontent.com/273688/62755553-27a03580-ba7d-11e9-85d6-ba10a8d9a819.jpg)

It's even worse on Chrome Beta 76.0.3809.89 , math is tiny and overlaps text with parts cut on 
![Screenshot_android_chrome](https://user-images.githubusercontent.com/273688/62755278-fbd08000-ba7b-11e9-8dba-16960a49ec0c.jpg)

In chrome, switching to desktop mode does nothing, same layout and same tiny and cut out math.

Browse v0.2.1.

**Comment by siddharths2710** [comment]
@mhl10 @cben Has this issue been resolved?  The mathjax formulas seem to appear at the right size now. Plus the mobile layout renders the page as expected too.

![arxiv_isue](https://user-images.githubusercontent.com/13200018/75941541-01793180-5eb6-11ea-8981-430513fcb148.jpg)

**Comment by siddharths2710** [comment]
@mhl10 @cben Does this issue still exist? The mathjax formulae seem to appear in the right size now.
![arxiv_isue](https://user-images.githubusercontent.com/13200018/75941688-59b03380-5eb6-11ea-8cdc-79d6bcfbebdf.jpg)

**Comment by mhl10** [comment]
Thanks for your message @siddharths2710. Though we are still working on additional improvements to the mobile presentation, I think we can close this issue. @SBBCornell, our UI/UX lead, may have some additional thoughts to share with you on this.

**Comment by SBBCornell** [comment]
Hi @siddharths2710. Were busy working on the new batch of mobile friendly updates for the abstract page and will be rolling them out to beta in the next month. If you are interested in previewing and giving feedback on the beta you might want to join our user testing list: https://arxiv.org/about/user-testing. We'd appreciate your feedback.

**Comment by ssriniv5** [comment]
@SBBCornell sure! I'd love to :D

**Comment by SBBCornell** [comment]
> @SBBCornell sure! I'd love to :D

Fantastic! Please sign up here and you'll be included in our next round of user testing: https://arxiv.org/about/user-testing

**Comment by cben** [comment]
Yep, formulas look great. (Android Chrome 81.0.4044.34, Firefox Preview
3.2.0)

чт, 5 мар. 2020 г., 19:42 Shamsi Brinn <notifications@github.com>:
