### ISSUE TITLE
bibtex export `primaryClass` field contains cruft

### ISSUE THREAD

**Issue by collares** [arXiv/arxiv-browse#644]
**Describe the bug**

arXiv's BibTeX exporting recently changed. Now, https://arxiv.org/bibtex/2406.16733 (for example) returns

```
@misc{dona2024diameter,
      title={The diameter of random Schreier graphs}, 
      author={Daniele Dona and Luca Sabatini},
      year={2024},
      eprint={2406.16733},
      archivePrefix={arXiv},
      primaryClass={id='math.CO' full_name='Combinatorics' is_active=True alt_name=None in_archive='math' is_general=False description='Discrete mathematics, graph theory, enumeration, combinatorial optimization, Ramsey theory, combinatorial game theory'}
}
```

The `primaryClass` field in particular contains more information than just `{math.CO}`, which is what I would expect.

**To Reproduce**

1. Go to https://arxiv.org/bibtex/2406.16733
2. See `primaryClass` field

**Expected behavior**
`primaryClass={math.CO}`, for example

**Comment by jweiskoff** [comment]
Thank you for pointing this out. We have created a work ticket for this bug.

**Comment by bdc34** [comment]
PR for this: https://github.com/arXiv/arxiv-browse/pull/645

**Comment by jweiskoff** [comment]
Deployed.
