### ISSUE TITLE
Missing date for new papers

### ISSUE THREAD

**Issue by cmbant** [arXiv/arxiv-browse#729]
As of today (20 Sept) the "New submissions for xxyyzz" at the top of the /new pages has disappeared, so there's no quick way to see when the list was last updated. (I also parse the /new page for my CosmoCoffee.info new-paper filter, since last time I looked no direct way to get this from the API). Restore the date in the header?

e.g. now shows just "new submissions" at

https://arxiv.org/list/astro-ph/new?skip=0&show=500#item0

**Comment by cmbant** [comment]
To be clear, this only seems to be an issue with explicit skip/show parameters.

**Comment by kyokukou** [comment]
Thank you for pointing out that the page was now missing helpful information. The date for new listings pages has been returned, now as an h3 near the top of the page.
